openapi: 3.0.3
info:
  title: Animati - OpenAPI 3.0
  description: ciao
  contact:
    email: assistenza@animati.app
  license:
    name: GPL-3.0 license
    url: https://github.com/IS-T51/animati/blob/main/LICENSE
  version: 0.3.0
servers:
- url: https://api.animati.app/
- url: http://localhost:8080/
tags:
- name: utente
- name: attivita
- name: liste
- name: etichette
paths:
  /utente:
    get:
      tags:
      - utente
      summary: Ottieni l'utente
      description: Ottieni l'utente associato alla sessione corrente
      operationId: getUtente
      responses:
        "200":
          description: L'utente associato alla sessione corrente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Utente'
        "401":
          description: Autenticazione necessaria per fare questa richiesta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "500":
          description: Errore interno del server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
      security:
      - autenticato: []
      x-swagger-router-controller: Utente
  /utenti:
    get:
      tags:
      - utente
      summary: Ottieni gli utenti
      description: Ottieni gli utenti iscritti all'applicativo
      operationId: getUtenti
      responses:
        "200":
          description: Lista di utenti
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Utente'
                x-content-type: application/json
        "401":
          description: Autenticazione necessaria per fare questa richiesta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "403":
          description: Non sei autorizzato a fare questa richiesta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "500":
          description: Errore interno del server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
      security:
      - autenticato: []
      x-swagger-router-controller: Utente
  /utente/{id}:
    patch:
      tags:
      - utente
      summary: Modifica il ruolo
      description: Modifica il ruolo dell'utente con l'id specificato
      operationId: modificaRuolo
      parameters:
      - name: id
        in: path
        description: L'id dell'utente
        required: true
        style: simple
        explode: false
        schema:
          pattern: "^[a-f\\d]{24}$"
          type: string
      - name: ruolo
        in: query
        description: Il nuovo ruolo dell'utente
        required: true
        style: form
        explode: true
        schema:
          type: string
          enum:
          - autenticato
          - amministratore
      responses:
        "200":
          description: Ruolo modificato
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Risposta'
        "400":
          description: Richiesta non valida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "401":
          description: Autenticazione necessaria per fare questa richiesta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "403":
          description: Non sei autorizzato a fare questa richiesta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "404":
          description: Utente non trovato
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "500":
          description: Errore interno del server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
      security:
      - autenticato: []
      x-swagger-router-controller: Utente
  /utente/login:
    get:
      tags:
      - utente
      summary: Effettua il login
      operationId: login
      responses:
        "302":
          description: Redirect alla pagina di login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Risposta'
        "500":
          description: Errore interno del server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
      x-swagger-router-controller: Utente
  /google:
    get:
      tags:
      - utente
      summary: Login con Google
      description: Verifica il codice autorizzativo fornito da Google e crea un utente
      operationId: loginGoogle
      parameters:
      - name: code
        in: query
        description: Il codice autorizzativo fornito da Google
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Login effettuato
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        "201":
          description: Registrazione effettuata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        "400":
          description: Richiesta non valida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "500":
          description: Errore interno del server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
      x-swagger-router-controller: Utente
  /attivita/{id}:
    get:
      tags:
      - attivita
      summary: Ottieni l'attività
      description: Ottieni l'attività con l'id specificato
      operationId: getAttivita
      parameters:
      - name: id
        in: path
        description: L'id dell'attività
        required: true
        style: simple
        explode: false
        schema:
          pattern: "^[a-f\\d]{24}$"
          type: string
      responses:
        "200":
          description: L'attività con l'id specificato
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Attivita'
        "404":
          description: L'attività non esiste
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "500":
          description: Errore interno del server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
      x-swagger-router-controller: Attivita
    put:
      tags:
      - attivita
      summary: Modifica l'attività
      description: Modifica l'attività con l'id specificato
      operationId: modificaAttivita
      parameters:
      - name: id
        in: path
        description: L'id dell'attività
        required: true
        style: simple
        explode: false
        schema:
          pattern: "^[a-f\\d]{24}$"
          type: string
      requestBody:
        description: L'attività modificata
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Attivita'
        required: true
      responses:
        "200":
          description: Attività modificata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Attivita'
        "400":
          description: Richiesta non valida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "401":
          description: Autenticazione necessaria per fare questa richiesta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "403":
          description: Non sei autorizzato a fare questa richiesta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "404":
          description: L'attività non esiste
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "500":
          description: Errore interno del server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
      security:
      - autenticato: []
      x-swagger-router-controller: Attivita
  /attivita/{id}/valutazione:
    get:
      tags:
      - attivita
      summary: Ottieni valutazione di un'attività
      description: Ottiene la valutazione dell'utente di un'attività
      operationId: ottieniValutazione
      parameters:
      - name: id
        in: path
        description: L'id dell'attività
        required: true
        style: simple
        explode: false
        schema:
          pattern: "^[a-f\\d]{24}$"
          type: string
      responses:
        "200":
          description: Valutazione dell'attività
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Valutazione'
        "204":
          description: Nessuna valutazione trovata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Risposta'
        "401":
          description: Autenticazione necessaria per fare questa richiesta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "404":
          description: Attività non trovata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "500":
          description: Errore interno del server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
      security:
      - autenticato: []
      x-swagger-router-controller: Attivita
    post:
      tags:
      - attivita
      summary: Aggiungi valutazione
      description: Aggiunge la valutazione all'attività
      operationId: aggiungiValutazione
      parameters:
      - name: id
        in: path
        description: L'id dell'attività
        required: true
        style: simple
        explode: false
        schema:
          pattern: "^[a-f\\d]{24}$"
          type: string
      requestBody:
        description: La valutazione da aggiungere
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Valutazione'
        required: true
      responses:
        "200":
          description: Valutazione aggiornata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Risposta'
        "201":
          description: Valutazione aggiunta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Risposta'
        "400":
          description: Richiesta non valida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "401":
          description: Autenticazione necessaria per fare questa richiesta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "404":
          description: Attività non trovata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "500":
          description: Errore interno del server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
      security:
      - autenticato: []
      x-swagger-router-controller: Attivita
  /attivita/{id}/segnalazioni:
    get:
      tags:
      - attivita
      summary: Ottieni segnalazioni di un'attività
      description: Ottiene tutte le segnalazioni in un'attività
      operationId: ottieniSegnalazioni
      parameters:
      - name: id
        in: path
        description: L'id dell'attività
        required: true
        style: simple
        explode: false
        schema:
          pattern: "^[a-f\\d]{24}$"
          type: string
      responses:
        "200":
          description: Lista di segnalazioni
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Segnalazione'
                x-content-type: application/json
        "204":
          description: Nessuna segnalazione trovata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Risposta'
        "401":
          description: Autenticazione necessaria per fare questa richiesta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "403":
          description: Non sei autorizzato a fare questa richiesta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "404":
          description: Attività non trovata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "500":
          description: Errore interno del server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
      security:
      - autenticato: []
      x-swagger-router-controller: Attivita
    post:
      tags:
      - attivita
      summary: Aggiungi segnalazione
      description: Aggiunge una segnalazione all'attività
      operationId: aggiungiSegnalazione
      parameters:
      - name: id
        in: path
        description: L'id dell'attività
        required: true
        style: simple
        explode: false
        schema:
          pattern: "^[a-f\\d]{24}$"
          type: string
      requestBody:
        description: La segnalazione da aggiungere
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Segnalazione'
        required: true
      responses:
        "201":
          description: Segnalazione aggiunta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Risposta'
        "400":
          description: Richiesta non valida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Risposta'
        "401":
          description: Autenticazione necessaria per fare questa richiesta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "404":
          description: Attività non trovata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "500":
          description: Errore interno del server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
      security:
      - autenticato: []
      x-swagger-router-controller: Attivita
  /catalogo:
    get:
      tags:
      - attivita
      summary: Ottieni il catalogo
      description: Ottieni il catalogo
      operationId: getCatalogo
      parameters:
      - name: informazioni
        in: query
        description: Filtra le attività per informazioni
        required: false
        style: form
        explode: true
        schema:
          $ref: '#/components/schemas/Informazioni'
      - name: autore
        in: query
        description: Filtra le attività per autore
        required: false
        style: form
        explode: true
        schema:
          pattern: "^[a-f\\d]{24}$"
          type: string
      - name: ultimaModificaMin
        in: query
        description: Filtra le attività per ultima modifica minima
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: date-time
      - name: ultimaModificaMax
        in: query
        description: Filtra le attività per ultima modifica massima
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: date-time
      - name: mediaValutazioniMin
        in: query
        description: Filtra le attività per media valutazioni minima
        required: false
        style: form
        explode: true
        schema:
          maximum: 10
          minimum: 1
          type: number
          format: double
      - name: mediaValutazioniMax
        in: query
        description: Filtra le attività per media valutazioni massima
        required: false
        style: form
        explode: true
        schema:
          maximum: 10
          minimum: 1
          type: number
          format: float
      - name: numeroSegnalazioniMin
        in: query
        description: Filtra le attività per numero segnalazioni minimo
        required: false
        style: form
        explode: true
        schema:
          minimum: 0
          type: integer
          format: int64
      - name: numeroSegnalazioniMax
        in: query
        description: Filtra le attività per numero segnalazioni massimo
        required: false
        style: form
        explode: true
        schema:
          minimum: 0
          type: integer
          format: int64
      - name: pagina
        in: query
        description: Pagina da visualizzare
        required: false
        style: form
        explode: true
        schema:
          minimum: 0
          type: integer
          format: int64
      - name: limite
        in: query
        description: Numero di attività per pagina
        required: false
        style: form
        explode: true
        schema:
          minimum: 0
          type: integer
          format: int64
      responses:
        "200":
          description: Il catalogo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Attivita'
                x-content-type: application/json
        "204":
          description: Nessuna attività presente nel catalogo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Risposta'
        "400":
          description: Richiesta non valida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "500":
          description: Errore interno del server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
      x-swagger-router-controller: Attivita
    post:
      tags:
      - attivita
      summary: Aggiungi l'attività
      description: Aggiungi l'attività al catalogo
      operationId: aggiungiAttivita
      requestBody:
        description: L'attività da aggiungere
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Attivita'
        required: true
      responses:
        "201":
          description: Attività aggiunta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Attivita'
        "400":
          description: Richiesta non valida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "401":
          description: Autenticazione necessaria per fare questa richiesta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "500":
          description: Errore interno del server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
      security:
      - autenticato: []
      x-swagger-router-controller: Attivita
  /catalogo/aggiorna:
    get:
      tags:
      - attivita
      summary: Aggiorna il catalogo
      description: Restituisce le attività aggiornate dopo la data specificata
      operationId: aggiornaCatalogo
      parameters:
      - name: data
        in: query
        description: La data dopo la quale cercare le attività aggiornate
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: date-time
      responses:
        "200":
          description: Attività da aggiornare
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Attivita'
                x-content-type: application/json
        "204":
          description: Nessuna attività da aggiornare
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Risposta'
        "400":
          description: Richiesta non valida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "500":
          description: Errore interno del server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
      x-swagger-router-controller: Attivita
  /liste:
    get:
      tags:
      - liste
      summary: Ottieni le liste
      description: Ottieni le liste dell'utente
      operationId: getListe
      responses:
        "200":
          description: Le liste dell'utente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lista'
        "401":
          description: Autenticazione necessaria per fare questa richiesta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "500":
          description: Errore interno del server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
      security:
      - autenticato: []
      x-swagger-router-controller: Liste
    post:
      tags:
      - liste
      summary: Crea lista
      description: Crea una nuova lista
      operationId: aggiungiLista
      requestBody:
        description: La lista da aggiungere
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lista'
        required: true
      responses:
        "201":
          description: Lista aggiunta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lista'
        "400":
          description: Richiesta non valida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "401":
          description: Autenticazione necessaria per fare questa richiesta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "500":
          description: Errore interno del server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
      security:
      - autenticato: []
      x-swagger-router-controller: Liste
  /lista/{id}:
    get:
      tags:
      - liste
      summary: Ottieni la lista
      description: Ottieni la lista con l'id specificato
      operationId: getLista
      parameters:
      - name: id
        in: path
        description: L'id della lista
        required: true
        style: simple
        explode: false
        schema:
          pattern: "^[a-f\\d]{24}$"
          type: string
      responses:
        "200":
          description: La lista con l'id specificato
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lista'
        "401":
          description: Autenticazione necessaria per fare questa richiesta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "403":
          description: Non sei autorizzato a fare questa richiesta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "404":
          description: Lista non trovata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "500":
          description: Errore interno del server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
      security:
      - autenticato: []
      x-swagger-router-controller: Liste
    post:
      tags:
      - liste
      summary: Aggiunge attività alla lista
      description: Aggiunge l'attività specificata alla lista
      operationId: aggiungiAttivitaALista
      parameters:
      - name: id
        in: path
        description: L'id della lista
        required: true
        style: simple
        explode: false
        schema:
          pattern: "^[a-f\\d]{24}$"
          type: string
      - name: attivita
        in: query
        description: L'id dell'attività da aggiungere alla lista
        required: true
        style: form
        explode: true
        schema:
          pattern: "^[a-f\\d]{24}$"
          type: string
      responses:
        "201":
          description: Attività aggiunta alla lista
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lista'
        "400":
          description: Richiesta non valida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "401":
          description: Autenticazione necessaria per fare questa richiesta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "403":
          description: Non sei autorizzato a fare questa richiesta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "404":
          description: Lista non trovata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "500":
          description: Errore interno del server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
      security:
      - autenticato: []
      x-swagger-router-controller: Liste
    delete:
      tags:
      - liste
      summary: Elimina lista
      description: Elimina la lista con l'id specificato
      operationId: eliminaLista
      parameters:
      - name: id
        in: path
        description: L'id della lista
        required: true
        style: simple
        explode: false
        schema:
          pattern: "^[a-f\\d]{24}$"
          type: string
      responses:
        "200":
          description: Lista eliminata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Risposta'
        "401":
          description: Autenticazione necessaria per fare questa richiesta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "403":
          description: Non sei autorizzato a fare questa richiesta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "404":
          description: Lista non trovata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "500":
          description: Errore interno del server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
      security:
      - autenticato: []
      x-swagger-router-controller: Liste
  /lista/{id}/{indice}:
    delete:
      tags:
      - liste
      summary: Rimuovi attività dalla lista
      description: Rimuove l'attività all'indice specificato dalla lista
      operationId: rimuoviAttivitaDaLista
      parameters:
      - name: id
        in: path
        description: L'id della lista
        required: true
        style: simple
        explode: false
        schema:
          pattern: "^[a-f\\d]{24}$"
          type: string
      - name: indice
        in: path
        description: L'indice dell'attività da rimuovere dalla lista
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Attività rimossa dalla lista
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lista'
        "400":
          description: Richiesta non valida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "401":
          description: Autenticazione necessaria per fare questa richiesta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "403":
          description: Non sei autorizzato a fare questa richiesta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "404":
          description: Lista non trovata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "500":
          description: Errore interno del server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
      security:
      - autenticato: []
      x-swagger-router-controller: Liste
  /etichette:
    get:
      tags:
      - etichette
      summary: Ottieni tutte le etichette
      description: Ottiene tutte le etichette
      operationId: ottieniEtichette
      responses:
        "200":
          description: Lista di etichette
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Etichetta'
                x-content-type: application/json
        "204":
          description: Nessuna etichetta trovata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Risposta'
        "500":
          description: Errore interno del server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
      x-swagger-router-controller: Etichette
    post:
      tags:
      - etichette
      summary: Aggiungi etichetta
      description: Aggiunge l'etichetta specificata
      operationId: aggiungiEtichetta
      requestBody:
        description: L'etichetta da aggiungere
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Etichetta'
        required: true
      responses:
        "200":
          description: Etichetta aggiornata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Etichetta'
        "201":
          description: Etichetta aggiunta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Etichetta'
        "400":
          description: Richiesta non valida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "401":
          description: Autenticazione necessaria per fare questa richiesta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "403":
          description: Non sei autorizzato a fare questa richiesta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
        "500":
          description: Errore interno del server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
      security:
      - autenticato: []
      x-swagger-router-controller: Etichette
  /ping:
    get:
      summary: Ping
      description: Ping
      operationId: ping
      responses:
        "200":
          description: Pong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Risposta'
        "418":
          description: I'm a teapot
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errore'
      x-swagger-router-controller: Default
components:
  schemas:
    Utente:
      required:
      - email
      - id
      - ruolo
      type: object
      properties:
        id:
          pattern: "^[a-f\\d]{24}$"
          type: string
          readOnly: true
        email:
          type: string
          format: email
          readOnly: true
        ruolo:
          type: string
          readOnly: true
          enum:
          - autenticato
          - amministratore
        promossoDa:
          pattern: "^[a-f\\d]{24}$"
          type: string
          readOnly: true
        immagine:
          maxLength: 512
          type: string
          description: Il link all'immagine dell'utente
          format: uri
          readOnly: true
      example:
        ruolo: autenticato
        promossoDa: 63b0201d249a3fa2cf566a4e
        id: 63b1b59a249a3fa2cf6989e6
        immagine: https://picsum.photos/700/400
        email: anonimo1@animati.app
    Attivita:
      required:
      - id
      type: object
      properties:
        id:
          pattern: "^[a-f\\d]{24}$"
          type: string
          readOnly: true
        banner:
          maxLength: 512
          type: string
          description: Il link al banner dell'attività
          format: uri
        informazioni:
          $ref: '#/components/schemas/Informazioni'
        collegamenti:
          type: array
          items:
            $ref: '#/components/schemas/Collegamento'
        ultimaModifica:
          type: string
          format: date-time
          readOnly: true
        autore:
          pattern: "^[a-f\\d]{24}$"
          type: string
          readOnly: true
        mediaValutazioni:
          maximum: 10
          minimum: 0
          type: number
          format: double
          readOnly: true
        numeroSegnalazioni:
          minimum: 0
          type: integer
          format: int64
          readOnly: true
      example:
        numeroSegnalazioni: 0
        ultimaModifica: 2000-01-23T04:56:07.000Z
        mediaValutazioni: 3.616076749251911
        banner: https://picsum.photos/700/400
        id: 63b189dbf6e4763b528548f4
        collegamenti:
        - link: http://example.com/aeiou
          nome: nome
        - link: http://example.com/aeiou
          nome: nome
        informazioni:
          etàMax: 1
          etichette:
          - etichette
          - etichette
          descrizione: descrizione
          etàMin: 1
          durataMin: 1
          titolo: titolo
          durataMax: 0
          giocatoriPerSquadra: 1
          numeroSquadre: 1
          giocatoriMax: 1
          giocatoriMin: 1
        autore: 63b1b59a249a3fa2cf6989e6
    Informazioni:
      type: object
      properties:
        titolo:
          maxLength: 20
          type: string
        descrizione:
          maxLength: 4096
          type: string
        etàMin:
          maximum: 99
          minimum: 1
          type: integer
          format: int64
        etàMax:
          maximum: 99
          minimum: 1
          type: integer
          format: int64
        durataMin:
          maximum: 9999
          minimum: 1
          type: integer
          format: int64
        durataMax:
          maximum: 9999
          minimum: 1
          type: integer
          format: int64
        giocatoriMin:
          maximum: 99
          minimum: 1
          type: integer
          format: int64
        giocatoriMax:
          maximum: 99
          minimum: 1
          type: integer
          format: int64
        giocatoriPerSquadra:
          maximum: 99
          minimum: 1
          type: integer
          format: int64
        numeroSquadre:
          maximum: 99
          minimum: 1
          type: integer
          format: int64
        etichette:
          type: array
          items:
            pattern: "[^,]{1,20}"
            type: string
      example:
        etàMax: 1
        etichette:
        - etichette
        - etichette
        descrizione: descrizione
        etàMin: 1
        durataMin: 1
        titolo: titolo
        durataMax: 1
        giocatoriPerSquadra: 1
        numeroSquadre: 1
        giocatoriMax: 1
        giocatoriMin: 1
    Etichetta:
      required:
      - categoria
      - descrizione
      - nome
      type: object
      properties:
        nome:
          pattern: "[^,]{1,20}"
          type: string
        descrizione:
          type: string
        categoria:
          type: string
      example:
        descrizione: descrizione
        categoria: categoria
        nome: nome
    Collegamento:
      required:
      - link
      - nome
      type: object
      properties:
        nome:
          maxLength: 128
          type: string
        link:
          maxLength: 512
          type: string
          format: uri
      example:
        link: http://example.com/aeiou
        nome: nome
    Lista:
      required:
      - id
      - nome
      type: object
      properties:
        id:
          pattern: "^[a-f\\d]{24}$"
          type: string
          readOnly: true
        nome:
          maxLength: 20
          minLength: 1
          type: string
        autore:
          pattern: "^[a-f\\d]{24}$"
          type: string
          readOnly: true
        attività:
          type: array
          readOnly: true
          items:
            pattern: "^[a-f\\d]{24}$"
            type: string
        ultimaModifica:
          type: string
          format: date-time
          readOnly: true
      example:
        attività:
        - 63b189dbf6e4763b528548f4
        - 63b189dbf6e4763b528548f4
        ultimaModifica: 2000-01-23T04:56:07.000Z
        nome: nome
        id: id
        autore: 63b1b59a249a3fa2cf6989e6
    Valutazione:
      required:
      - attività
      - voto
      type: object
      properties:
        voto:
          maximum: 10
          minimum: 1
          type: integer
          format: int64
        attività:
          pattern: "^[a-f\\d]{24}$"
          type: string
          readOnly: true
        autore:
          pattern: "^[a-f\\d]{24}$"
          type: string
          readOnly: true
      example:
        attività: 63b189dbf6e4763b528548f4
        voto: 1
        autore: 63b1b59a249a3fa2cf6989e6
    Segnalazione:
      required:
      - autore
      - messaggio
      - titolo
      type: object
      properties:
        messaggio:
          maxLength: 500
          minLength: 1
          type: string
        titolo:
          maxLength: 50
          minLength: 1
          type: string
        attività:
          pattern: "^[a-f\\d]{24}$"
          type: string
          readOnly: true
        autore:
          pattern: "^[a-f\\d]{24}$"
          type: string
          readOnly: true
      example:
        attività: 63b189dbf6e4763b528548f4
        titolo: titolo
        messaggio: messaggio
        autore: 63b1b59a249a3fa2cf6989e6
    Errore:
      required:
      - code
      - messaggio
      type: object
      properties:
        code:
          type: integer
          format: int64
          readOnly: true
          enum:
          - 401
          - 403
          - 404
          - 418
          - 500
          default: 401
        messaggio:
          maxLength: 128
          minLength: 1
          type: string
          readOnly: true
          default: Autenticazione necessaria per fare questa richiesta
        errori:
          type: array
          readOnly: true
          items:
            type: object
    Risposta:
      required:
      - codice
      - messaggio
      type: object
      properties:
        codice:
          type: integer
          format: int64
          readOnly: true
          enum:
          - 200
          - 201
          - 204
          - 302
        messaggio:
          maxLength: 128
          minLength: 1
          type: string
          readOnly: true
      example:
        messaggio: ok
        codice: 200
    Token:
      allOf:
      - $ref: '#/components/schemas/Risposta'
      - type: object
        properties:
          token:
            type: string
            readOnly: true
            example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAwMDAwMDAwMDAwMDAwMDAwMDAwIiwiZW1haWwiOiJ0ZXN0QGFuaW1hdGkuYXBwIiwiaW1tYWdpbmUiOiJodHRwczovL3d3dy5hbmltYXRpLmFwcC9hc3NldHMvaW1nL2xvZ285Ni5wbmciLCJydW9sbyI6ImFtbWluaXN0cmF0b3JlIiwicHJvbW9zc29EYSI6IjAwMDAwMDAwMDAwMDAwMDAwMDAwIn0.7VUJK3mbI014Tvkjr6AwJhjCPo5tTPBRmuuLsYJa61c
  securitySchemes:
    autenticato:
      type: http
      scheme: bearer
      bearerFormat: JWT
